[package]
name = "url_shortener_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
openssl-sys = "0.9.101"
reqwest = "0.12.1"
urlshortener = "3.2.0"
